name: socket_probe
description: "A flutter application for testing websocket connections."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # state management
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7

  # network connection
  web_socket_channel: ^3.0.2
  socket_io_client: ^3.0.2

  # screen and utils
  bitsdojo_window: ^0.1.6
  intl: ^0.20.2
  json_editor: ^0.0.8

  get_it: ^8.0.3
  regex_router: ^2.0.2
  iconsax: ^0.0.8
  url_launcher: ^6.3.1

  mocktail: ^1.0.4
 

dev_dependencies:
  bloc_test: ^10.0.0

  flutter_launcher_icons: "^0.14.3"
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - shorebird.yaml

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/static/Nunito-Regular.ttf
